name: Build ZMK firmware

on:
  workflow_dispatch:  # can be triggered manually
  push:
    paths-ignore:
      - 'images/**'
      - 'keymap-drawer.config.yaml'
      - 'keymap/**'
      - 'docs/**'
      - '.vscode/**'
      - 'README.md'
      - '.gitattributes'
      - '.gitignore'
      - 'flake.nix'
      - 'flake.lock'
      - 'justfile'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
